FROM nginx

COPY ./etc/nginx/ssl /etc/nginx/ssl
COPY ./etc/nginx/server_name.conf /etc/nginx/server_name.conf
COPY ./etc/nginx/conf.d /etc/nginx/conf.d
COPY ./etc/nginx/nginx.conf /etc/nginx/nginx.conf
